[workspace]
channels = ["conda-forge"]
name = "MTCargo_analysis"
platforms = ['osx-arm64', "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
numpy = ">=2.3.5,<3"
scipy = ">=1.17.0,<2"
pandas = ">=3.0.0,<4"
matplotlib = ">=3.10.8,<4"
trackpy = ">=0.7,<0.8"
scikit-image = ">=0.26.0,<0.27"
opencv = ">=4.13.0,<5"
numba = ">=0.64.0,<0.65"
jupyterlab = ">=4.5.3,<5"
ipympl = ">=0.10.0,<0.11"
tqdm = ">=4.67.2,<5"
ipykernel = ">=7.1.0,<8"
pip = ">=26.0,<27"
pyfftw = ">=0.15.1,<0.16"

[pypi-dependencies]
annotated-types = "*"
anyio = "*"
appnope = "*"
argon2-cffi = "*"
argon2-cffi-bindings = "*"
arrow = "*"
asttokens = "*"
async-lru = "*"
attrs = "*"
babel = "*"
beautifulsoup4 = "*"
bleach = "*"
certifi = "*"
cffi = "*"
charset-normalizer = "*"
click = "*"
cloudpickle = "*"
comm = "*"
contourpy = "*"
cycler = "*"
dask = "*"
debugpy = "*"
decorator = "*"
defusedxml = "*"
donfig = "*"
executing = "*"
fastjsonschema = "*"
fonttools = "*"
fqdn = "*"
fsspec = "*"
google-crc32c = "*"
h11 = "*"
httpcore = "*"
httpx = "*"
idna = "*"
ImageIO = "*"
ipykernel = "*"
ipython = "*"
ipython_pygments_lexers = "*"
ipywidgets = "*"
isoduration = "*"
jedi = "*"
Jinja2 = "*"
joblib = "*"
json5 = "*"
jsonpointer = "*"
jsonschema = "*"
jsonschema-specifications = "*"
jupyter-events = "*"
jupyter-lsp = "*"
jupyter_client = "*"
jupyter_core = "*"
jupyter_server = "*"
jupyter_server_terminals = "*"
jupyterlab_pygments = "*"
jupyterlab_server = "*"
jupyterlab_widgets = "*"
kiwisolver = "*"
lark = "*"
lazy_loader = "*"
locket = "*"
looseversion = "*"
MarkupSafe = "*"
matplotlib-inline = "*"
mistune = "*"
nbclient = "*"
nbconvert = "*"
nbformat = "*"
nd2 = "*"
nest-asyncio = "*"
networkx = "*"
notebook_shim = "*"
numcodecs = "*"
ome-types = "*"
packaging = "*"
pandocfilters = "*"
parso = "*"
partd = "*"
pexpect = "*"
pillow = "*"
platformdirs = "*"
prometheus_client = "*"
prompt_toolkit = "*"
psutil = "*"
ptyprocess = "*"
pure_eval = "*"
pycparser = "*"
pydantic = "*"
pydantic-extra-types = "*"
pydantic_core = "*"
Pygments = "*"
pyparsing = "*"
python-dateutil = "*"
python-json-logger = "*"
pytz = "*"
PyYAML = "*"
pyzmq = "*"
referencing = "*"
requests = "*"
resource-backed-dask-array = "*"
rfc3339-validator = "*"
rfc3986-validator = "*"
rfc3987-syntax = "*"
rpds-py = "*"
Send2Trash = "*"
setuptools = "*"
six = "*"
soupsieve = "*"
stack-data = "*"
terminado = "*"
tifffile = "*"
tinycss2 = "*"
toolz = "*"
tornado = "*"
traitlets = "*"
typing-inspection = "*"
typing_extensions = "*"
tzdata = "*"
uri-template = "*"
urllib3 = "*"
wcwidth = "*"
webcolors = "*"
webencodings = "*"
websocket-client = "*"
widgetsnbextension = "*"
xsdata = "*"
zarr = "*"
